### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by tymondeusz** [martinkarlweber/rcraid-patches#1] opened 2018-06-22 13:34 UTC
Hi mawerick / Martin,
Please find below. It may be one of the dependencies. The manual is so messy. Driver is for 16.04 but when it comes to dependencies it only mentions 15.10. As I explained in https://community.amd.com/thread/227801 according to your manual I have successfully patched the driver according to the output but it won't build. 

> Hi tymondeusz,
can you please send the output of the following commands:
gcc --version
uname -a
cat /etc/lsb_release

`gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0`
`Linux NZXT 4.15.0-23-generic #25-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`
`cat: /etc/lsb_release: No such file or directory`
`sudo apt install lsb-release 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
lsb-release is already the newest version (9.20170808ubuntu1).`

[Output.zip](https://github.com/martinkarlweber/rcraid-patches/files/2127809/Output.zip)

**Comment by martinkarlweber** [comment] 2018-06-24 13:06
Hi tymondeusz,

from the output you send me I see that you are using Ubuntu 18.04, is it right? I see two issues from the output you sent me: First of all, the script src/common.sh is not sourced from the install script. Secondly, the usage of PIE should not happen. The problems might be related. Therefore I think it is best to first solve the first issue, and if you still have problems, contact me again. 

Here is what I recommend you should try: Instead of `sudo sh install` please try `sudo /bin/bash install`. If `bash` is not installed (should be if you are running a standard Ubuntu installation) go ahead and install it.

**Comment by tymondeusz** [comment] 2018-06-26 21:28
Hello Martin, 

Thanks for your response. 

Yes, this is a brand new install of Ubuntu 18.04 and nothing has been done to it except for the installation of chrome and some updates. I've tried `sudo /bin/bash install` and the results are the same. 
[Output01.zip](https://github.com/martinkarlweber/rcraid-patches/files/2138983/Output01.zip)

With regards to the points you've raised: 
> First of all, the script src/common.sh is not sourced from the install script.

I have no idea why the script would misbehave. I literally downloaded the latest version from AMD and after initially failing I installed your patch. I understand that your patch worked for you on a clean copy of 18.04 but perhaps this is an issue with an update that happened after you were successful and released it? Don't know.

With regards to the other issue: PIE i have been googling around and found that this may be an issue with GCC (Or rather with the software not being up to the new standard. It seems that PIE is now enabled by default in GCC. I tried to add flags within the install script to disable it but don't see that working either. Actually upon inspection I see that I either didn't save changes or I did that with another copy of the installer. 

Regards
Tim

**Comment by martinkarlweber** [comment] 2018-06-30 23:53
Hi Tim,

it is good to see that /bin/bash solved the first problem. The thing is that in earlier Linux versions /bin/sh was indeed a link to /bin/bash. Now it is a link to /bin/dash, and some of the features of bash get lost. This should have been fixed by the AMD developers since long, but the driver also is very old and not maintained. I will include it in my next release. 

Now back to the other problem. I downloaded the latest Ubuntu 18.04 image, installed it on a USB stick and booted in UEFI mode. After booting, I downloaded and installed the same AMD RAID driver as you did, installed my patch and it worked. Thus I cannot reproduce your problem. Here are the steps I took to get it running, after downloading the AMD RAID driver from the AMD support page.
 
`cd Downloads/`
`unzip raid_linux_driver_8_01_00_039_public.zip`
`sudo apt install git`
`git clone https://github.com/martinkarlweber/rcraid-patches.git`
`mv rcraid-patches/rcraid.patch .`
`rm -rf rcraid-patches/`
`patch -p0 < rcraid.patch`
`cd driver_sdk/`
`sudo apt install build-essential`
`sudo /bin/bash ./install`
`sudo rmmod ahci libahci`
`sudo modprobe rcraid`
`dmesg | less`

It is really strange that you get this error. Did you make any changes to the default kernel (`make cloneconfig` or `make menuconfig`)? 

In any case, I have created a new patch file that forces `gcc` not to use PIE by adding the `no-pie` flag to the Makefile. You can find the file in the branch `no-pie` at [this link](https://github.com/martinkarlweber/rcraid-patches/blob/no-pie/rcraid.patch). If that does not help, maybe go ahead and compare the configurations. Here is the configuration of my running system:

`$ uname -a`
`Linux picard 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
`$ cat /etc/lsb-release `
`DISTRIB_ID=Ubuntu`
`DISTRIB_RELEASE=18.04`
`DISTRIB_CODENAME=bionic`
`DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"`
`$ gcc -v`
`Using built-in specs.`
`COLLECT_GCC=gcc`
`COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper`
`OFFLOAD_TARGET_NAMES=nvptx-none`
`OFFLOAD_TARGET_DEFAULT=1`
`Target: x86_64-linux-gnu`
`Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-16ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --with-as=/usr/bin/x86_64-linux-gnu-as --with-ld=/usr/bin/x86_64-linux-gnu-ld --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu`
`Thread model: posix`
`gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)`

I hope you can find a difference and this points to a solution. I am using an ASUS PRIME B350plus motherboard with a AMD Ryzen 5 1500X Quad-Core Processor.

**Comment by tymondeusz** [comment] 2018-07-05 10:00
Hello Martin, 
Big thanks for getting back to me again, 
Now, before I continue I'd like to ask you about your config itself. I've also been in touch with AMD with regards to that and they had warned me, that the Linux driver only supports a full-raid setup, where both SATA and the NVME M.2 drives are raided. They claim that my configuration won't work as I only use RAID on the SATA controllers for mass storage and I run my OS off a singular NVME M.2 in AHCI mode.  Funny enough I don't even have a different option and if I do it's still hidden in the BIOS. I only have one switch in BIOS that switches AHCI to RAID and it only ever affects the SATA controllers. 
Can you please tell me how you've got your drives configured? 

Regards
Tim

**Comment by martinkarlweber** [comment] 2018-07-05 21:19
Hi Tim,

my setup is two 2 TB SATA disks with RAID 1 and an additional SATA DVDRAM drive outside of the RAID. All my data are on the RAID. I am not using NVME M.2; however I would be interested to migrate my OS to a faster SSD in the future and only store data on the RAID.

Regards,

Martin

**Comment by tymondeusz** [comment] 2018-07-05 21:26
Well,
AMD claims that with the current drivers it's impossible to use a
combination of raid and non raid devices, but they told me to keep an eye
out for an updated driver. Nothing specific, but sounds like a promise. I
need to make sure I won't make my os unbootable before continuing with
experiments :D

Regards

**Comment by martinkarlweber** [comment] 2018-07-07 14:43
Hi Tim, what I can confirm is that you cannot use both the `ahci` and `rcraid` kernel modules, this is why I had to `rmmod ahci` kernel module before `modprobe rcraid`. However, my DVD drive runs from the rcraid driver although it is not RAIDed. It is true that after switching off the SCM module in the UEFI, the DVD drive is no longer seen by the `ahci` driver and only accessible via the `rcraid` kernel module. I guess that will be true for any drive and this is what they want to say. Turning the SCM module off also means you have to switch to a GPT compliant partition table. But since I am not using NVME M.2 interface, I do not think I can help you further.

In my opinion you could try booting with a Ubuntu 18.04 USB installation, compile and insert the `rcraid` kernel module and check what happens. I did this several times switching back and forth UEFI settings to find out what worked for me. I had no problems with data loss on my disks, but it is always good to keep a recent backup.

**Comment by martinkarlweber** [comment] 2018-09-16 12:25
Closing this bug now since the problem could not be reproduced. If anybody can send confirming evidence, please open the bug again.

**Closed as completed by martinkarlweber** 2018-09-16 12:25 UTC

**Comment by tymondeusz** [comment] 2019-04-02 21:26
Hello Martin, 

Sorry about the long delay! I have been super busy at work and had to forget about this for a while.
Your updated script and instructions worked for me and I am SOOO SOO CLOSE to gaining access to my array (I think). 

I still have a hiccup when modprobing rcraid and I was hoping you could help me as I couldn't find nothing relating to my problem on the webs for the past few hours. 
when I modprobe rcraid I now get: 

```
rcraid: loading out-of-tree module taints kernel.
rcraid: module license 'Proprietary' taints kernel.
Disabling lock debugging due to kernel taint
rcraid: module verification failed: signature and/or required key missing - tainting kernel
<5>AMD, Inc. rcraid raid driver version 8.1.0 build_number 8.1.0-00039 built Apr 02 2019
<5>rcraid built on NZXT by root on Tue  2 Apr 20:59:38 BST 2019
<5>rcraid: cmd_q_depth 512, tag_q_depth 16, max_xfer 448, use_swl 0xffffffff
<5>rcraid_probe_one: vendor = 0x1022 device 0x43bd
<5>rcraid_probe_one: vendor = 0x1022 device 0x7916
<5>rcraid_probe_one: Total adapters matched 2
<5>rcraid: rc_init_adapter 64 bit DMA enabled
<6>### rc_init_adapter(): RC_EnableZPODD = 0
<3>rcraid:0 request_threaded_irq irq 74
<5>rcraid: card 0: AMD, Inc. AHCI
```

I must be missing something as I don't see anything relating to attaching devices, like in your manual: 
```
sd 0:0:0:0: Attached scsi generic sg1 type 0
  sd 0:0:0:0: [sdb] 3905925120 512-byte logical blocks: (2.00 TB/1.82 TiB)
  sd 0:0:0:0: [sdb] Write Protect is off
  sd 0:0:0:0: [sdb] Mode Sense: 00 06 00 00
  sd 0:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
```

I noticed that after a reboot the ahci modules are still loaded but when I unload them and modprobe rcraid I get the same thing as above: 

```
tski@NZXT:~$ sudo lsmod | grep ahci
[sudo] password for tski: 
ahci                   40960  0
libahci                32768  1 ahci
tski@NZXT:~$ sudo rmmod ahci libahci
tski@NZXT:~$ sudo modprobe rcraid
tski@NZXT:~$ dmesg | less
tski@NZXT:~$ dmesg | grep rcraid
[    1.592724] rcraid: loading out-of-tree module taints kernel.
[    1.592730] rcraid: module license 'Proprietary' taints kernel.
[    1.593451] rcraid: module verification failed: signature and/or required key missing - tainting kernel
[    1.594388] <5>AMD, Inc. rcraid raid driver version 8.1.0 build_number 8.1.0-00039 built Apr 02 2019
[    1.594389] <5>rcraid built on NZXT by root on Tue  2 Apr 20:59:38 BST 2019
[    1.594390] <5>rcraid: cmd_q_depth 512, tag_q_depth 16, max_xfer 448, use_swl 0xffffffff
[    1.594476] <5>rcraid_probe_one: vendor = 0x1022 device 0x43bd
[    1.594479] <5>rcraid_probe_one: vendor = 0x1022 device 0x7916
[    1.594479] <5>rcraid_probe_one: Total adapters matched 2
[    1.594921] <5>rcraid: rc_init_adapter 64 bit DMA enabled
[    1.594983] <3>rcraid:0 request_threaded_irq irq 74
[    1.594987] <5>rcraid: card 0: AMD, Inc. AHCI
```

Regards

**Comment by tymondeusz** [comment] 2019-04-03 15:17
Martin, 

By poking around I realised that though my install was relatively fresh it wasn't clean anymore. I must have been poking around it and installed some software, then forgotten about it until the next time I logged in to ubuntu. I just tried your instructions on a live USB and it worked fine, so I reinstalled ubuntu from scratch and again it worked like a charm. 

Because I'm somewhat lazy I've put your instructions into a bash script that when put in the same folder as the ZIP will install updates (apt update && apt upgrade) and install the driver. 
As a thank you for your help in the past please take it as my contribution. May it help others.

Regards,
Tim

```
#!/bin/bash
echo "Unzipping archive"
sleep 2
unzip raid_linux_driver_8_01_00_039_public.zip
echo "Installing tools"
sleep 2
sudo apt update && sudo apt -y upgrade && sudo apt -y install git build-essential
echo "Downloading patch"
sleep 2
git clone https://github.com/martinkarlweber/rcraid-patches.git
echo "Installing patch"
sleep 2
mv rcraid-patches/rcraid.patch .
rm -rf rcraid-patches/
patch -p1 < rcraid.patch
cd driver_sdk/
sudo /bin/bash ./install
echo "Removing ahci modules"
sleep 2
sudo rmmod ahci libahci
echo "Initialising raid module"
sleep 2
sudo modprobe rcraid
echo "Checking logs to confirm success..."
sleep 3
dmesg | less

```
